FROM eclipse-temurin:21-jre

WORKDIR /app
COPY target/MessagingSystem-0.0.1-SNAPSHOT.jar MessagingSystem-0.0.1-SNAPSHOT.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "MessagingSystem-0.0.1-SNAPSHOT.jar"]

